[id="selecting-right-distribution']
= Distribution selection

Red Hat provides several distributions of OpenJDK. This module will hep you select the distribution that's right for your needs.

OpenJDK RPMs for RHEL 7::
Red Hat provides RPM distributions of OpenJDK 7, 8, and 11 for RHEL 7. These OpenJDK 7 and 8 distributions can also be installed as a JRE. These distributions provide Java Web Start. The OpenJDK 11 distribution includes Flight Recorder for support of Mission Control.
OpenJDK RPMs for RHEL 8::
Red Hat provides RPM distributions of OpenJDK 8 and 11 for RHEL 8. The OpenJDK 8 distribution can be installed as a JRE. These distributions provide Java Web Start. The OpenJDK 11 distribution includes Flight Recorder for support of Mission Control.
OpenJDK 8 JRE Portable Zip for RHEL::
Red Hat provides a portable OpenJDK 8 JRE Zip distribution for RHEL 7 and 8 hosts.
OpenJDK 8 Portable Zip for RHEL::
Red Hat provides a portable OpenJDK 8 Zip distribution for RHEL 7 and 8 hosts.
OpenJDK 11 Portable Zip for RHEL::
Red Hat provides a portable OpenJDK 11 Zip distribution for RHEL 7 and 8 hosts. This distribution includes Flight Recorder for support of Mission Control.
OpenJDK 8 Zip for Windows::
OpenJDK 8 distribution for all supported Windows hosts. Includes Java Web Start, Mission Control and Flight Recorder.
OpenJDK 11 Zip for Windows::
OpenJDK 11 distribution for all supported Windows hosts. Includes Java Web Start, Mission Control and Flight Recorder.
OpenJDK 8 Installer for Windows::
OpenJDK 8 MSI installer for all supported Windows hosts. Optionally installs Java Web Start and sets environment variables.
OpenJDK 11 Installer for Windows::
OpenJDK 1 MSI installer for all supported Windows hosts. Optionally installs Java Web Start and sets environment variables.

.Additional resources
JDK Mission Control is available for RHEL from link:https://access.redhat.com/documentation/en-us/red_hat_software_collections/3/html/3.2_release_notes/chap-RHSCL#tabl-RHSCL-Components[Red Hat Software Collections 3.2].
