[id="rhel_select_jdk_rpm"]
= Selecting a specific JDK on {rhel} installed with RPMs

If you have multiple JDKs installed on {rhel} you can select a
specific JDK using the `alternatives` command. Selecting the JDK by using this
approach changes the default `java` and `javac` system wide. Changing these settings
will require root privileges.
See xref:proc-rhel-setting-java-home-env-variable.adoc[setting `JAVA_HOME` variable]
documentation if you need to select a specific JDK without root privileges.

.Prerequisites
* root privileges on the system.
* xref:proc-rhel-installing-multiple-major-versions.adoc[Have multiple JDKs installed] on your system using the `yum` package manager.

.Procedure
. See the automatically selected JDK before switching to a different one
+
----
# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
# javac -version
javac 1.8.0_212
----
+
. Show commands available via `alternatives`
+
----
# alternatives --list
libnssckbi.so.x86_64	auto	/usr/lib64/pkcs11/p11-kit-trust.so
ld	auto	/usr/bin/ld.bfd
mta	auto	/usr/sbin/sendmail.sendmail
emacs.etags	auto	/usr/bin/etags.emacs
emacs	auto	/usr/bin/emacs-24.3
java	auto	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/bin/java
jre_openjdk	auto	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
jre_11	auto	/usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64
jre_11_openjdk	auto	/usr/lib/jvm/jre-11-openjdk-11.0.3.7-0.el7_6.x86_64
jre_1.8.0	auto	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
jre_1.8.0_openjdk	auto	/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64
----
+
. Interactively select the desired binary using `alternatives --config _<name>_`
+
----
# alternatives --config java
There are 2 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
   1           java-11-openjdk.x86_64 (/usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/java)
*+ 2           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/bin/java)

Enter to keep the current selection[+], or type selection number: 1
----
. Verify that the binary has been changed as desired
+
----
# java -version
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3+7-LTS, mixed mode, sharing)
----
+
. Repeat the `alternatives --config` step for `javac`

[NOTE]
====
By switching the `javac` master `alternatives` link many slave links for binaries provided
by the `-devel` sub-package will switch too.
====
