[id="proc-windows-installing_openjdk_zip"]
= Installing {prod} with the ZIP file

The easiest way to install the JDK on windows via the command prompt.

[NOTE]
====
Extracting the contents of the ZIP bundle to a directory path that *does not* contain spaces is recommended.

This is important as many scripts that reference the JAVA_HOME environment variable may not extract the path correctly if their is a space present.
====


.Procedure
. link:{openjdk-download-url}[Download the ZIP bundle] of {comp}.
. Extract the contents of the ZIP bundle to a directory of your choice.  See the note and caution above about spaces in the install path.
. Update the PATH as below:
----
C:\> setx /m PATH "%PATH%;${YOUR_INSTALL_PATH}\bin"
----
[NOTE]
====
The above command only works if you start the command prompt with `Run as administrator`.

/m updates the value as a system wide setting, instead of the default local environment.

You have to restart the command prompt to check the setting by typing `path`.
====
[start=4]
. The `%JAVA_HOME%` environment variable must also be set to use some developer tools.

Set the `%JAVA_HOME%` environment variable as
----
C:\> setx /m JAVA_HOME "${YOUR_INSTALL_PATH}"
----
[NOTE]
====
JAVA_HOME will *NOT* work if the bin directory is appended to ${YOUR_INSTALL_PATH}.

After restarting the command prompt, you can view your setting by typing `echo %JAVA_HOME%`.
====

include::modules/proc_add-java-home-env-variable.adoc[]
