[id="rhel_installing_openjdk_jre_archive"]
= Installing the JRE with the archive bundle on {rhel}

The Java Runtime Environment (JRE) can be manually installed using the {archive} bundle.
This is useful if the Java administrator does not have root privileges on the system.
Note that it's recommended to create a parent directory containing your JREs and create a symlink to the latest JRE via a generic path.
This eases upgrades to later versions.

.Procedure
. link:{openjdk-rhel-archive-download-url}[Download the JRE {archive} bundle] of {comp}.
. Extract the contents of the {archive} bundle to a directory of your choice.
+
[source,subs="+quotes"]
----
$ mkdir ~/jres && cd ~/jres
$ tar -xf _`<tar-file>`_
----
+
. Create a generic path by using symlinks to your JRE for easier upgrades
+
[source,subs="+quotes"]
----
$ ln -s ~/jres/_`<your-directory>`_ ~/jres/_`<major-version>`_
----
+
. Add the `bin` directory of the generic JRE path to the `PATH` environment variable:
+
[source,subs="+quotes"]
----
$ export PATH="$PATH:$(echo ~)/jres/_`<major-version>`_/bin"
----
+
. Verify that `java -version` works without supplying the full path:
+
----
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181.-b13, mixed mode)
----
+

// Example URL: https://access.redhat.com/solutions/1445833 (for JAVA_HOME)
. In order to persist the `PATH` variable setting use these instructions: _`<add-link-to-RHEL-bashrc-path-link>`_

. The `JAVA_HOME` environment variable must also be set to use some developer tools.

include::../modules/snip-rhel-setting-java-home.adoc[]
