[id="rhel_updating_openjdk_zip_bundle"]
= Updating {prod} for RHEL with ZIP Bundle

{comp} can be manually installed using the ZIP bundle.

.Procedure
. link:{openjdk-rhel-archive-download-url}[Download the {archive} bundle] of {comp}.
. Extract the contents of the {archive} bundle to a directory of your choice.
+
[NOTE]
====
Extracting the contents of the ZIP bundle to a directory path that *does not* contain spaces is recommended.
====
+
----
$ tar -xf java-11-openjdk-11.0.3.7-0.tar.xz
----
+

. Add `bin` directory contained in your {comp} installation path to the `PATH` environment variable:
+
----
$ export PATH="/home/openjdk/java-11-openjdk-11.0.3.7-0.el6.static.jdk.openjdkportable.x86_64/bin"
----
+

. Verify that `java -version` works without supplying the full path
+
----
$ java -version
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment (build 11.0.3+7-LTS)
OpenJDK 64-bit Server VM (build 11.0.3+7-LTS, mixed mode)
----
+

// Example URL: https://access.redhat.com/solutions/1445833 (for JAVA_HOME)
. In order to persist the `PATH` variable setting use these instructions: _`<add-link-to-RHEL-bashrc-path-link>`_

The `JAVA_HOME` environment variable must also be set to use some developer tools.
Set the `JAVA_HOME` environment variable as follows:

include::modules/proc-rhel-setting-java-home-env-variable.adoc[]
