[id="rhel_installing_openjdk_archive"]
= Installing the Java Development Kit with the archive bundle on {rhel}

The Java Development Kit (JDK) can be manually installed using the {archive} bundle.
This is useful if the Java administrator does not have root privileges on the system.

NOTE: It is recommended to create a parent directory containing your JDKs and
create a symlink to the latest JDK via a generic path. This eases upgrades to
later versions.


.Procedure
. link:{openjdk-rhel-archive-download-url}[Download the JDK {archive} bundle] of {comp}.
. Extract the contents of the {archive} bundle to a directory of your choice.
+
----
$ mdkir ~/jdks && cd ~/jdks
$ tar -xf java-11-openjdk-11.0.3.7-0.tar.xz
----
+
. Create a generic path by using symlinks to your JDK for easier upgrades
+
----
$ ln -s ~/jdks/java-11-openjdk-11.0.3.7-0.el6.static.jdk.openjdkportable.x86_64 ~/jdks/java-11
----
+
. Add the `bin` directory of the generic JDK path to the `PATH` environment variable:
+
----
$ export PATH="$PATH:$(echo ~)/jdks/java-11"
----
+
. Verify that `javac -version` works without supplying the full path:
+
----
$ javac -version
javac 11.0.3
----
+

// Example URL: https://access.redhat.com/solutions/1445833 (for JAVA_HOME)
. In order to persist the `PATH` variable setting use these instructions: _`<add-link-to-RHEL-bashrc-path-link>`_

The `JAVA_HOME` environment variable must also be set to use some developer tools.
Set the `JAVA_HOME` environment variable as follows:

include::../modules/proc-rhel-setting-java-home-env-variable.adoc[]
