[id="rhel_installing_openjdk_jre_archive"]
= Installing the JDK with the archive bundle on {rhel}

The Java Runtime Environment (JRE) can be manually installed using the {archive} bundle.
This is useful if the Java administrator does not have root privileges on the system.

.Procedure
. link:{openjdk-rhel-archive-download-url}[Download the JRE {archive} bundle] of {comp}.
. Extract the contents of the {archive} bundle to a directory of your choice.
+
[source,subs="+quotes"]
----
$ tar -xf _`<tar-file>`_
----
+
. Add the `bin` directory contained in your {comp} installation path to the `PATH` environment variable:
+
[source,subs="+quotes"]
----
$ export PATH="/home/openjdk/_`<your-directory>`_/bin"
----
+
. Verify that `java -version` works without supplying the full path:
+
----
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181.-b13, mixed mode)
----
+

// Example URL: https://access.redhat.com/solutions/1445833 (for JAVA_HOME)
. In order to persist the `PATH` variable setting use these instructions: _`<add-link-to-RHEL-bashrc-path-link>`_

The `JAVA_HOME` environment variable must also be set to use some developer tools.
Set the `JAVA_HOME` environment variable as follows:

include::modules/proc-rhel-setting-java-home-env-variable.adoc[]
